Repository WildCodeSchool/orleans-0919-php-synops, pull requests merged in 2019-12, with the labels that each got.

#17 Layout défault (scss, base, layouts)
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  package.json
  templates/base.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  yarn.lock
Labels: Reviewed

#20 quand faire appel à Syn'ops ?
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/home.scss
  assets/scss/home/call.scss
  src/Controller/HomeController.php
  templates/home/call.html.twig
  templates/home/index.html.twig
Labels: Corrections done

#22 S01 us22 concretely
  assets/scss/app.scss
  assets/scss/home.scss
  assets/scss/home/call.scss
  assets/scss/home/concretely.scss
  templates/home/call.html.twig
  templates/home/concretely.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#23 fix margin mobile
  assets/scss/home/concretely.scss
Labels: Reviewed

#25 Fix extends
  templates/home/_call.html.twig
  templates/home/_concretely.html.twig
  templates/home/call.html.twig
  templates/home/concretely.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#24 S01 us23 adn
  assets/scss/home.scss
  assets/scss/home/adn.scss
  templates/home/_adn.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#21 S01 us01
  assets/scss/admin/admin_article.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  phpmd.xml
  src/Controller/AdminArticleController.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  src/Repository/ArticleRepository.php
  symfony.lock
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_article/show.html.twig
Labels: Reviewed

#27 S01 us23 engagements
  assets/js/app.js
  assets/scss/home.scss
  assets/scss/home/engagements.scss
  composer.lock
  package.json
  public/images/compass_white.png
  templates/home/_engagements.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#30 FIX suppression layout et block
  templates/home/_engagements.html.twig
Labels: Reviewed

#26 S01 us24 carousel
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/carousel.scss
  public/images/MultiFonction.webp
  public/images/Phare.webp
  public/images/bateau.webp
  templates/home/carousel.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#28 S01 us20 navbar
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/navbar_style.scss
  composer.json
  composer.lock
  config/bundles.php
  package.json
  public/images/LOGO_CARRE_BLANC.png
  src/Controller/HomeController.php
  symfony.lock
  templates/_navbar.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  yarn.lock
Labels: Reviewed

#33 S01 us03 crud delete
  src/Controller/AdminArticleController.php
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/index.html.twig
Labels: Reviewed

#32 EDIT OK
  assets/scss/admin/admin_article.scss
  src/Controller/AdminArticleController.php
  src/Entity/Article.php
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
Labels: Reviewed

#34 dev to master
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/admin/admin_article.scss
  assets/scss/app.scss
  assets/scss/carousel.scss
  assets/scss/home.scss
  assets/scss/home/adn.scss
  assets/scss/home/call.scss
  assets/scss/home/concretely.scss
  assets/scss/home/engagements.scss
  assets/scss/navbar_style.scss
  composer.json
  composer.lock
  config/bundles.php
  package.json
  phpmd.xml
  public/images/LOGO_CARRE_BLANC.png
  public/images/MultiFonction.webp
  public/images/Phare.webp
  public/images/bateau.webp
  public/images/compass_white.png
  src/Controller/AdminArticleController.php
  src/Controller/HomeController.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  src/Repository/ArticleRepository.php
  symfony.lock
  templates/_navbar.html.twig
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_article/show.html.twig
  templates/base.html.twig
  templates/home/_adn.html.twig
  templates/home/_call.html.twig
  templates/home/_concretely.html.twig
  templates/home/_engagements.html.twig
  templates/home/carousel.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  yarn.lock
Labels: Reviewed

#31 S01 us21 footer
  assets/scss/app.scss
  assets/scss/footer.scss
  templates/home/_footer.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
Labels: Reviewed

#36 S01 us02 crud edit fix
  templates/admin_article/index.html.twig
Labels: Reviewed

#37 S01 us19 team
  assets/scss/_vars.scss
  assets/scss/home.scss
  assets/scss/home/call.scss
  assets/scss/home/team.scss
  templates/home/_team.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#35 Fix carrousel + chemins images
  assets/images/LOGO_CARRE_BLANC.png
  assets/images/bateau.webp
  assets/images/compass_white.png
  assets/images/multifonction.webp
  assets/images/phare.webp
  templates/_navbar.html.twig
  templates/home/_carousel.html.twig
  templates/home/_engagements.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#38 dev to master
  assets/images/LOGO_CARRE_BLANC.png
  assets/images/bateau.webp
  assets/images/compass_white.png
  assets/images/multifonction.webp
  assets/images/phare.webp
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/footer.scss
  assets/scss/home.scss
  assets/scss/home/call.scss
  assets/scss/home/team.scss
  templates/_navbar.html.twig
  templates/admin_article/index.html.twig
  templates/home/_carousel.html.twig
  templates/home/_engagements.html.twig
  templates/home/_footer.html.twig
  templates/home/_team.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: Reviewed

#39 S01 us21 footer fix
  templates/home/_footer.html.twig
Labels: Reviewed

#52 fichier eslint
  .eslintrc.yml
Labels: Reviewed

#55 S02 us30 page index admin
  assets/images/bg-index.webp
  assets/scss/admin.scss
  assets/scss/admin/index.scss
  assets/scss/app.scss
  src/Controller/AdminArticleController.php
  src/Controller/AdminIndexController.php
  templates/admin/index.html.twig
Labels: Reviewed

#57 path admin_article
  src/Controller/AdminArticleController.php
Labels: Reviewed

#58 S02 us29
  assets/scss/app.scss
  assets/scss/home.scss
  assets/scss/home/article.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/Controller/HomeController.php
  src/DataFixtures/ArticleFixtures.php
  symfony.lock
  templates/home/_article.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#54 S02 us09 partners add
  .gitignore
  assets/scss/_vars.scss
  config/packages/twig.yaml
  src/Controller/AdminPartnerController.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Repository/PartnerRepository.php
  templates/admin_partner/_delete_form.html.twig
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  templates/admin_partner/show.html.twig
Labels: Reviewed

#56 S02 us31 navbar admin
  assets/scss/admin.scss
  templates/admin/_navbar.html.twig
  templates/admin_article/index.html.twig
  templates/layout_admin.html.twig
Labels: Changes request

#60 S02 fix style article admin
  assets/scss/admin.scss
  assets/scss/admin/admin_article.scss
  assets/scss/app.scss
  templates/admin_article/_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
Labels: Reviewed

#62 S02 us35
  composer.json
  composer.lock
  config/bundles.php
  config/packages/stof_doctrine_extensions.yaml
  src/Controller/HomeController.php
  src/Entity/Article.php
  symfony.lock
Labels: Reviewed

#63 S02_US29_Fix_Responsive (home card)
  assets/scss/home/article.scss
Labels: Reviewed

#65 S02 us33 partners (home)
  assets/scss/home.scss
  assets/scss/home/partners.scss
  src/Controller/HomeController.php
  templates/home/_partners.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#64 S02US10 Edit partner
  src/Controller/AdminPartnerController.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Partner.php
  templates/admin/_navbar.html.twig
  templates/admin_partner/_delete_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
Labels: Reviewed

#61 S02 us32 actus
  assets/scss/app.scss
  assets/scss/article.scss
  assets/scss/home/article.scss
  src/Controller/ArticleController.php
  templates/article/list.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#67 Contrast navbar, responsive typo, delete dropdown effect and one less media querie :D
  assets/scss/_vars.scss
  assets/scss/home.scss
  assets/scss/navbar_style.scss
  templates/_navbar.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#68 dev to master
  .eslintrc.yml
  .gitignore
  assets/images/bg-index.webp
  assets/scss/_vars.scss
  assets/scss/admin.scss
  assets/scss/admin/admin_article.scss
  assets/scss/admin/index.scss
  assets/scss/app.scss
  assets/scss/article.scss
  assets/scss/home.scss
  assets/scss/home/article.scss
  assets/scss/home/partners.scss
  assets/scss/navbar_style.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/stof_doctrine_extensions.yaml
  config/packages/twig.yaml
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/Controller/AdminArticleController.php
  src/Controller/AdminIndexController.php
  src/Controller/AdminPartnerController.php
  src/Controller/ArticleController.php
  src/Controller/HomeController.php
  src/DataFixtures/ArticleFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Article.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Repository/PartnerRepository.php
  symfony.lock
  templates/_navbar.html.twig
  templates/admin/_navbar.html.twig
  templates/admin/index.html.twig
  templates/admin_article/_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_partner/_delete_form.html.twig
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  templates/admin_partner/show.html.twig
  templates/article/list.html.twig
  templates/home/_article.html.twig
  templates/home/_footer.html.twig
  templates/home/_partners.html.twig
  templates/home/index.html.twig
  templates/layout_admin.html.twig
Labels: Reviewed

#69 S02 fix carousel
  assets/images/lighthouse.webp
  assets/images/phare.webp
  templates/home/_carousel.html.twig
Labels: Reviewed

#72 dev to master
  assets/images/lighthouse.webp
  assets/images/phare.webp
  assets/scss/_vars.scss
  assets/scss/navbar_style.scss
  templates/_navbar.html.twig
  templates/home/_carousel.html.twig
Labels: Reviewed

#73 S02 us34 show
  assets/scss/article.scss
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/Controller/ArticleController.php
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#71 S01 us26 offres
  .gitignore
  assets/scss/home.scss
  assets/scss/home/deal.scss
  src/Controller/HomeController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/ToolFixtures.php
  src/Entity/Category.php
  src/Entity/Tool.php
  src/Migrations/.gitignore
  src/Repository/CategoryRepository.php
  src/Repository/ToolRepository.php
  templates/home/_deal.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#87 S03 us18 Contact Form (fonctionnalité et CSS OK)
  assets/js/app.js
  assets/scss/app.scss
  assets/scss/contact.scss
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  templates/contact/index.html.twig
Labels: Reviewed

#88 S03 us14 user connexion
  assets/scss/app.scss
  assets/scss/login.scss
  assets/scss/navbar_style.scss
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthentificator.php
  templates/_navbar.html.twig
  templates/security/login.html.twig
Labels: Reviewed
