Repository WildCodeSchool/orleans-0919-php-synops, pull requests merged in 2020-01, with the labels that each got.

#89 sending contact mail is ok
  .env
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/swiftmailer.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/swiftmailer.yaml
  config/services.yaml
  src/Controller/ContactController.php
  src/Form/ContactType.php
  symfony.lock
  templates/base.html.twig
  templates/contact/email/notification.html.twig
  templates/contact/index.html.twig
  templates/flash_messages.html.twig
  templates/layout_mail.html.twig
Labels: Reviewed

#90 dev to master
  .env
  .gitignore
  assets/js/app.js
  assets/scss/app.scss
  assets/scss/article.scss
  assets/scss/contact.scss
  assets/scss/home.scss
  assets/scss/home/deal.scss
  assets/scss/login.scss
  assets/scss/navbar_style.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/swiftmailer.yaml
  config/packages/security.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/swiftmailer.yaml
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/Controller/ArticleController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/ToolFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Category.php
  src/Entity/Contact.php
  src/Entity/Tool.php
  src/Entity/User.php
  src/Form/ContactType.php
  src/Migrations/.gitignore
  src/Repository/CategoryRepository.php
  src/Repository/ToolRepository.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthentificator.php
  symfony.lock
  templates/_navbar.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/base.html.twig
  templates/contact/email/notification.html.twig
  templates/contact/index.html.twig
  templates/flash_messages.html.twig
  templates/home/_article.html.twig
  templates/home/_deal.html.twig
  templates/home/index.html.twig
  templates/layout_mail.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#91 ajouts/changements d'images (photos de l'équipe, carrousel, appel)
  assets/images/anne.webp
  assets/images/bottle.webp
  assets/images/canoe.webp
  assets/images/multifonction.webp
  assets/images/quitterie.webp
  assets/scss/home/call.scss
  templates/home/_call.html.twig
  templates/home/_carousel.html.twig
  templates/home/_team.html.twig
Labels: Reviewed

#92 liens sur la nav (logo, offre, équipe)
  templates/_navbar.html.twig
Labels: Reviewed

#94 add envelop contact sticky
  templates/_navbar.html.twig
Labels: Reviewed

#93 liens vers les réseaux sociaux
  templates/_navbar.html.twig
  templates/home/_footer.html.twig
  templates/home/_team.html.twig
Labels: Reviewed

#97 fix contact title
  templates/contact/index.html.twig
Labels: Reviewed

#98 fix flash message contact page
  templates/flash_messages.html.twig
Labels: Reviewed

#102 S03 titles
  templates/admin/index.html.twig
  templates/admin_article/index.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/new.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#101 Link to Synops PDF
  assets/PDF/plaquette.pdf
  templates/home/_engagements.html.twig
  webpack.config.js
Labels: Reviewed

#105 dev to master
  assets/PDF/plaquette.pdf
  assets/images/anne.webp
  assets/images/bottle.webp
  assets/images/canoe.webp
  assets/images/multifonction.webp
  assets/images/quitterie.webp
  assets/scss/home/call.scss
  templates/_navbar.html.twig
  templates/admin/index.html.twig
  templates/admin_article/index.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/new.html.twig
  templates/contact/index.html.twig
  templates/flash_messages.html.twig
  templates/home/_call.html.twig
  templates/home/_carousel.html.twig
  templates/home/_engagements.html.twig
  templates/home/_footer.html.twig
  templates/home/_team.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#103 S03 us25 inscription
  .gitignore
  assets/scss/app.scss
  assets/scss/register.scss
  src/Controller/SecurityController.php
  src/Form/RegistrationFormType.php
  templates/security/login.html.twig
  templates/security/register.html.twig
Labels: Reviewed

#106 Fix shadow under the navbar.
  assets/scss/navbar_style.scss
Labels: Reviewed

#125 Square around pictures. Easy.
  assets/scss/home/team.scss
  templates/home/_team.html.twig
Labels: Reviewed

#127 Roles allowed
  config/packages/security.yaml
Labels: Reviewed

#128 favicon
  assets/images/favicon.ico
  templates/base.html.twig
Labels: Reviewed

#129 Change class of profile pictures
  assets/scss/home/team.scss
  templates/home/_team.html.twig
Labels: Reviewed

#107 S03 us7 crud outil
  assets/scss/admin.scss
  assets/scss/admin/admin_tool.scss
  composer.lock
  src/Controller/AdminToolController.php
  src/Entity/Tool.php
  src/Form/ToolType.php
  templates/admin/_navbar.html.twig
  templates/admin_tool/_delete_form.html.twig
  templates/admin_tool/_form.html.twig
  templates/admin_tool/edit.html.twig
  templates/admin_tool/index.html.twig
  templates/admin_tool/new.html.twig
  templates/admin_tool/show.html.twig
Labels: Reviewed

#126 wiziwig article
  assets/scss/home/article.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  package.json
  src/Form/ArticleType.php
  symfony.lock
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/home/_article.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#138 S04 us27 flèche haut bas home
  assets/scss/app.scss
  assets/scss/arrow.scss
  templates/home/index.html.twig
Labels: Reviewed

#99 S03 us13 tools
  assets/scss/app.scss
  assets/scss/home/carousel.scss
  assets/scss/pages/article.scss
  assets/scss/pages/contact.scss
  assets/scss/pages/login.scss
  assets/scss/pages/tools.scss
  src/Controller/ContactController.php
  src/Controller/SecurityController.php
  src/Controller/ToolController.php
  src/DataFixtures/ToolFixtures.php
  src/Entity/Category.php
  src/Entity/Tool.php
  src/Form/ToolType.php
  templates/_navbar.html.twig
  templates/home/_deal.html.twig
  templates/tool/index.html.twig
Labels: Reviewed

#140 S04 us27 back to top
  templates/_backToTop.html.twig
  templates/admin_article/index.html.twig
  templates/admin_partner/index.html.twig
  templates/article/list.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#104 S03 us15 affichage esp client
  assets/scss/member.scss
  composer.json
  composer.lock
  src/Controller/MemberController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Category.php
  src/Entity/User.php
  templates/user/show.html.twig
Labels: Reviewed

#145 S03 fix articles
  assets/scss/app.scss
  assets/scss/home/article.scss
  src/Entity/Category.php
Labels: Reviewed

#147 dev to master
  .gitignore
  assets/images/favicon.ico
  assets/scss/admin.scss
  assets/scss/admin/admin_tool.scss
  assets/scss/app.scss
  assets/scss/arrow.scss
  assets/scss/home/article.scss
  assets/scss/home/carousel.scss
  assets/scss/home/team.scss
  assets/scss/member.scss
  assets/scss/navbar_style.scss
  assets/scss/pages/article.scss
  assets/scss/pages/contact.scss
  assets/scss/pages/login.scss
  assets/scss/pages/tools.scss
  assets/scss/register.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  config/packages/security.yaml
  package.json
  src/Controller/AdminToolController.php
  src/Controller/ContactController.php
  src/Controller/MemberController.php
  src/Controller/SecurityController.php
  src/Controller/ToolController.php
  src/DataFixtures/ToolFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Category.php
  src/Entity/Tool.php
  src/Entity/User.php
  src/Form/ArticleType.php
  src/Form/RegistrationFormType.php
  src/Form/ToolType.php
  symfony.lock
  templates/_backToTop.html.twig
  templates/_navbar.html.twig
  templates/admin/_navbar.html.twig
  templates/admin_article/index.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_tool/_delete_form.html.twig
  templates/admin_tool/_form.html.twig
  templates/admin_tool/edit.html.twig
  templates/admin_tool/index.html.twig
  templates/admin_tool/new.html.twig
  templates/admin_tool/show.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/base.html.twig
  templates/home/_article.html.twig
  templates/home/_deal.html.twig
  templates/home/_team.html.twig
  templates/home/index.html.twig
  templates/security/login.html.twig
  templates/security/register.html.twig
  templates/tool/index.html.twig
  templates/user/show.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#150 S04 us35 redirection connexion
  src/Controller/MemberController.php
  src/Controller/ToolController.php
  templates/_navbar.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#151 S04 routes fr
  src/Controller/AdminArticleController.php
  src/Controller/AdminPartnerController.php
  src/Controller/ArticleController.php
  src/Controller/CommentController.php
  src/Controller/SecurityController.php
  templates/_navbar.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#152 US40 - Admin / List Members
  assets/scss/admin/admin_members.scss
  assets/scss/app.scss
  src/Controller/AdminUserController.php
  src/Entity/Category.php
  src/Entity/User.php
  templates/admin/_navbar.html.twig
  templates/admin_member/_delete_form.html.twig
  templates/admin_member/index.html.twig
Labels: Reviewed

#153 Fix comment assert
  src/Entity/Comment.php
Labels: Reviewed

#155 rangement plus propre du CSS
  assets/scss/_arrow.scss
  assets/scss/_footer.scss
  assets/scss/_navbar_style.scss
  assets/scss/admin.scss
  assets/scss/app.scss
  assets/scss/home.scss
  assets/scss/member.scss
  assets/scss/pages.scss
  assets/scss/pages/register.scss
Labels: Priority, Reviewed

#156 US 41 - Admin delete member
  templates/admin_member/index.html.twig
Labels: Reviewed

#157 Change message if you are already connected.
  templates/security/login.html.twig
Labels: Reviewed

#154 S04 fix customerspace
  src/Controller/CustomerSpaceController.php
  templates/user/show.html.twig
Labels: Priority, Reviewed

#158 S04 us43 upload
  .gitignore
  assets/scss/admin.scss
  assets/scss/admin/admin_article.scss
  assets/scss/home/article.scss
  assets/scss/pages/article.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  src/DataFixtures/ArticleFixtures.php
  src/Entity/Article.php
  src/Form/ArticleType.php
  symfony.lock
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/base.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#160 S04 fix admin members
  assets/scss/admin.scss
  assets/scss/admin/admin_members.scss
  templates/admin_member/index.html.twig
Labels: Reviewed

#161 S04 fix affichage home
  assets/scss/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#165 dev to master
  .gitignore
  assets/scss/_arrow.scss
  assets/scss/_footer.scss
  assets/scss/_navbar_style.scss
  assets/scss/_vars.scss
  assets/scss/admin.scss
  assets/scss/admin/admin_article.scss
  assets/scss/admin/admin_members.scss
  assets/scss/app.scss
  assets/scss/home.scss
  assets/scss/home/article.scss
  assets/scss/member.scss
  assets/scss/pages.scss
  assets/scss/pages/article.scss
  assets/scss/pages/register.scss
  assets/scss/pages/tools.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  src/Controller/AdminArticleController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminUserController.php
  src/Controller/ArticleController.php
  src/Controller/CommentController.php
  src/Controller/CustomerSpaceController.php
  src/Controller/SecurityController.php
  src/Controller/ToolController.php
  src/DataFixtures/ArticleFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Article.php
  src/Entity/Category.php
  src/Entity/Comment.php
  src/Entity/User.php
  src/Form/ArticleType.php
  src/Form/CommentType.php
  src/Repository/CommentRepository.php
  symfony.lock
  templates/_navbar.html.twig
  templates/admin/_navbar.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_member/_delete_form.html.twig
  templates/admin_member/index.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/base.html.twig
  templates/comment/_delete_form.html.twig
  templates/comment/_form.html.twig
  templates/home/_article.html.twig
  templates/home/index.html.twig
  templates/security/login.html.twig
  templates/tool/index.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#149 S04 us36 pagination
  assets/scss/home/article.scss
  src/Controller/ArticleController.php
  src/Repository/ArticleRepository.php
  templates/article/list.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#159 boucle render navbar
  config/packages/framework.yaml
  src/Controller/ContactController.php
  src/Controller/CustomerSpaceController.php
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
  src/Controller/ToolController.php
  templates/_categories_in_nav.html.twig
  templates/_navbar.html.twig
Labels: Reviewed

#163 fix bug d'affichage cache
  templates/user/show.html.twig
Labels: Reviewed

#164 logos partenaires en noir & blanc, couleur au passage de la souris
  assets/scss/home/partners.scss
Labels: Reviewed

#162 US 42 - Admin validate member
  assets/scss/admin.scss
  src/Controller/AdminUserController.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  templates/admin_member/index.html.twig
Labels: Reviewed

#166 dev to master
  assets/scss/admin.scss
  assets/scss/home/article.scss
  assets/scss/home/partners.scss
  config/packages/framework.yaml
  src/Controller/AdminUserController.php
  src/Controller/ArticleController.php
  src/Controller/ContactController.php
  src/Controller/CustomerSpaceController.php
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
  src/Controller/ToolController.php
  src/DataFixtures/UserFixtures.php
  src/Repository/ArticleRepository.php
  templates/_categories_in_nav.html.twig
  templates/_navbar.html.twig
  templates/admin_member/index.html.twig
  templates/article/list.html.twig
  templates/home/_article.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#167 title article show
  src/DataFixtures/ArticleFixtures.php
  templates/article/show.html.twig
Labels: Reviewed

#168 changer 'client' pour 'membre', demande des clientes
  templates/_navbar.html.twig
Labels: Reviewed

#169 Fix title of waiting members
  templates/admin_member/index.html.twig
Labels: Reviewed

#170 dev to master
  src/DataFixtures/ArticleFixtures.php
  templates/_navbar.html.twig
  templates/admin_member/index.html.twig
  templates/article/show.html.twig
Labels: Reviewed

#172 US 39 Admin Edit member
  src/Controller/AdminUserController.php
  templates/admin_member/index.html.twig
Labels: Reviewed

#190 Mise a jour du formulaire d'inscription.
  assets/scss/pages/register.scss
  src/Form/RegistrationFormType.php
  templates/security/register.html.twig
Labels: Reviewed

#192 US 16 - Reset password
  assets/scss/pages/login.scss
  composer.json
  composer.lock
  src/Controller/ResettingController.php
  src/Entity/User.php
  src/Form/ResettingType.php
  templates/resetting/index.html.twig
  templates/resetting/mail.html.twig
  templates/resetting/request.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#193 S04 us45 crud edit document
  src/Controller/AdminDocumentController.php
  templates/admin_document/edit.html.twig
  templates/admin_tool/edit.html.twig
  templates/admin_tool/index.html.twig
Labels: Reviewed

#194 S04 us46 crud delete document
  src/Controller/AdminDocumentController.php
  templates/admin_document/_delete_form.html.twig
  templates/admin_document/index.html.twig
  templates/admin_document/show.html.twig
  templates/admin_tool/index.html.twig
Labels: Reviewed

#195 S05 fix pics
  assets/scss/admin.scss
  assets/scss/admin/admin_partners.scss
  assets/scss/app.scss
  assets/scss/home/engagements.scss
  templates/admin_partner/index.html.twig
Labels: Reviewed

#196 US 55 - Agree terms
  src/Controller/SecurityController.php
  src/Form/RegistrationFormType.php
  templates/security/register.html.twig
  templates/security/terms.html.twig
Labels: Reviewed

#198 Upload file CSV members
  src/Controller/AdminUserController.php
  templates/admin_member/export_user.csv.twig
  templates/admin_member/index.html.twig
Labels: Reviewed

#201 S05 us49 team read
  src/Controller/AdminTeamController.php
  src/Controller/HomeController.php
  src/DataFixtures/TeamFixtures.php
  src/Entity/Team.php
  src/Form/TeamType.php
  src/Repository/TeamRepository.php
  templates/admin_team/_delete_form.html.twig
  templates/admin_team/_form.html.twig
  templates/admin_team/edit.html.twig
  templates/admin_team/index.html.twig
  templates/admin_team/new.html.twig
  templates/admin_team/show.html.twig
  templates/home/_team.html.twig
Labels: Reviewed

#202 US 52 - Delete comments
  src/Controller/CommentController.php
  src/Controller/ToolController.php
  src/Entity/Category.php
  src/Entity/Comment.php
  templates/comment/_delete_form.html.twig
  templates/tool/index.html.twig
Labels: Reviewed

#203 Error pages OK
  assets/images/bg-error.webp
  assets/scss/app.scss
  assets/scss/pages.scss
  assets/scss/pages/errors.scss
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/layout_errors.html.twig
Labels: Reviewed

#204 S05 us49 team create
  src/Form/TeamType.php
  templates/admin_team/index.html.twig
  templates/admin_team/new.html.twig
  templates/home/_team.html.twig
Labels: Correction in progress

#205 Flash color and placement.
  assets/scss/_navbar_style.scss
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/flash_messages.html.twig
  templates/tool/index.html.twig
Labels: Reviewed

#207 Framing team pictures
  assets/scss/home/team.scss
Labels: Reviewed

#206 S05 us44 add upload document
  .gitignore
  assets/scss/admin/admin_tool.scss
  config/packages/vich_uploader.yaml
  src/DataFixtures/DocumentFixtures.php
  src/Entity/Document.php
  src/Form/DocumentType.php
  templates/admin_document/edit.html.twig
  templates/admin_tool/index.html.twig
Labels: Reviewed

#208 S05 us38 edit profil
  assets/scss/pages.scss
  assets/scss/pages/customer-space.scss
  src/Controller/AdminToolController.php
  src/Controller/UserController.php
  src/Form/UserType.php
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#209 Notification inactif members six months
  src/Entity/User.php
  templates/admin_member/index.html.twig
Labels: Reviewed

#213 ajout d'un lien vers le panneau d'admin
  src/Controller/AdminIndexController.php
  templates/home/index.html.twig
Labels: Reviewed

#214 Suppression des documents liés à la suppression d'un outil
  src/Entity/Tool.php
Labels: Reviewed

#215 S05 us49 team update
  src/Controller/AdminTeamController.php
  src/Entity/Team.php
  src/Form/TeamType.php
  templates/admin_team/_delete_form.html.twig
  templates/admin_team/_form.html.twig
  templates/admin_team/edit.html.twig
  templates/admin_team/index.html.twig
Labels: Reviewed

#216 S05 us49 team delete
  src/Controller/AdminTeamController.php
  templates/admin_team/_delete_form.html.twig
  templates/admin_team/index.html.twig
Labels: Reviewed

#217 upload partners
  .gitignore
  assets/scss/admin/admin_partners.scss
  config/packages/vich_uploader.yaml
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  templates/home/_partners.html.twig
Labels: Reviewed

#219 dev to master
  .gitignore
  assets/scss/admin/admin_partners.scss
  config/packages/vich_uploader.yaml
  src/Controller/AdminIndexController.php
  src/Controller/AdminTeamController.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Partner.php
  src/Entity/Team.php
  src/Entity/Tool.php
  src/Form/PartnerType.php
  src/Form/TeamType.php
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  templates/admin_team/_delete_form.html.twig
  templates/admin_team/_form.html.twig
  templates/admin_team/edit.html.twig
  templates/admin_team/index.html.twig
  templates/home/_partners.html.twig
  templates/home/index.html.twig
Labels: Priority, Reviewed

#220 afficher les document avec les fichiers dans la boite à outils
  templates/tool/index.html.twig
Labels: Reviewed

#218 S05 us49 team upload
  config/packages/vich_uploader.yaml
  src/Controller/AdminTeamController.php
  src/DataFixtures/TeamFixtures.php
  src/Entity/Team.php
  src/Form/TeamType.php
  templates/admin_team/edit.html.twig
  templates/admin_team/index.html.twig
  templates/admin_team/new.html.twig
  templates/home/_team.html.twig
Labels: Reviewed

#221 dev to master
  config/packages/vich_uploader.yaml
  src/Controller/AdminTeamController.php
  src/DataFixtures/TeamFixtures.php
  src/Entity/Team.php
  src/Form/TeamType.php
  templates/admin_team/edit.html.twig
  templates/admin_team/index.html.twig
  templates/admin_team/new.html.twig
  templates/home/_team.html.twig
  templates/tool/index.html.twig
Labels: Reviewed

#223 fix team photo and flash message
  src/Entity/Team.php
  templates/admin/_navbar.html.twig
  templates/admin_team/index.html.twig
Labels: Reviewed

#222 S05 fix tools (vraies sous-catégories + faux documents)
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/DocumentFixtures.php
  src/DataFixtures/ToolFixtures.php
  templates/admin_partner/index.html.twig
Labels: Reviewed

#225 add section to article
  config/packages/framework.yaml
  src/Controller/AdminSectionController.php
  src/Entity/Article.php
  src/Entity/Section.php
  src/Form/ArticleType.php
  src/Form/SectionType.php
  src/Repository/SectionRepository.php
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_section/_delete_form.html.twig
  templates/admin_section/_form.html.twig
  templates/admin_section/edit.html.twig
  templates/admin_section/index.html.twig
  templates/admin_section/new.html.twig
  templates/admin_section/show.html.twig
Labels: Reviewed

#226 update article section
  src/Controller/AdminSectionController.php
  templates/admin_article/edit.html.twig
  templates/admin_section/edit.html.twig
Labels: Reviewed

#228 index admin section
  templates/admin_section/index.html.twig
Labels: Reviewed

#230 delete section
  src/Entity/Section.php
  templates/admin_section/_delete_form.html.twig
  templates/admin_section/edit.html.twig
Labels: Reviewed

#232 fix links
  templates/_navbar.html.twig
  templates/home/_team.html.twig
Labels: Reviewed

#233 mise en place des fixtures pour la section des articles
  src/DataFixtures/ArticleFixtures.php
  src/DataFixtures/SectionFixtures.php
Labels: Reviewed

#234 Femeture div
  templates/admin_article/edit.html.twig
Labels: Reviewed

#236 S05 fix standardization admin
  assets/scss/admin/admin_article.scss
  assets/scss/admin/admin_members.scss
  assets/scss/admin/admin_partners.scss
  assets/scss/admin/admin_tool.scss
  src/Entity/Document.php
  templates/admin_article/_delete_form.html.twig
  templates/admin_article/_form.html.twig
  templates/admin_article/edit.html.twig
  templates/admin_article/index.html.twig
  templates/admin_article/new.html.twig
  templates/admin_document/_delete_form.html.twig
  templates/admin_document/_form.html.twig
  templates/admin_document/edit.html.twig
  templates/admin_document/new.html.twig
  templates/admin_member/_delete_form.html.twig
  templates/admin_member/index.html.twig
  templates/admin_partner/_delete_form.html.twig
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  templates/admin_partner/show.html.twig
  templates/admin_tool/_delete_form.html.twig
  templates/admin_tool/_form.html.twig
  templates/admin_tool/edit.html.twig
  templates/admin_tool/index.html.twig
  templates/admin_tool/new.html.twig
  templates/admin_tool/show.html.twig
Labels: Reviewed

#237 Liste des articles en fonction de la section et du titre
  src/Controller/ArticleController.php
  src/Form/ArticleSearchType.php
  src/Repository/ArticleRepository.php
  templates/article/list.html.twig
Labels: Reviewed

#238 Contenu article admin
  templates/admin_article/index.html.twig
Labels: Reviewed

#235 description Equipe
  templates/admin_team/index.html.twig
Labels: Reviewed

#239 S05 us60 mime icon
  src/Controller/AdminToolController.php
  src/DataFixtures/DocumentFixtures.php
  src/Entity/Document.php
  templates/admin_tool/index.html.twig
Labels: Reviewed

#240 Margin home page
  templates/home/index.html.twig
Labels: Reviewed

#241 fix section article (button)
  templates/admin_article/index.html.twig
Labels: Reviewed

#242 mode opératoire admin
  assets/images/bg-index.webp
  assets/scss/admin/index.scss
  templates/admin/index.html.twig
Labels: Reviewed

#243 afficher un icone dans la vue de l'index outil
  templates/admin_tool/index.html.twig
Labels: Reviewed

#244 Icon outil client fix
  templates/tool/index.html.twig
Labels: Reviewed

#245 fix front admin sections + equipe
  assets/scss/admin.scss
  templates/admin/index.html.twig
  templates/admin_article/index.html.twig
  templates/admin_section/_delete_form.html.twig
  templates/admin_section/_form.html.twig
  templates/admin_section/edit.html.twig
  templates/admin_section/index.html.twig
  templates/admin_section/new.html.twig
  templates/admin_section/show.html.twig
  templates/admin_team/_delete_form.html.twig
  templates/admin_team/_form.html.twig
  templates/admin_team/edit.html.twig
  templates/admin_team/index.html.twig
  templates/admin_team/new.html.twig
Labels: Reviewed

#247 Fix engagements
  assets/scss/home/engagements.scss
  templates/home/_engagements.html.twig
Labels: Reviewed

#248 Fix envoi mail
  config/services.yaml
  config/services_dev.yaml
  src/Controller/ContactController.php
Labels: Reviewed

#249 rechercher en FR
  src/Form/ArticleSearchType.php
  templates/article/list.html.twig
Labels: Reviewed

#250 ajout d'un bouton dans la section admin pour revenir sur les articles
  templates/admin_section/index.html.twig
Labels: Reviewed

#251 dev to master
  .github/workflows/main.yml
  assets/scss/home/engagements.scss
  config/services.yaml
  config/services_dev.yaml
  src/Controller/ContactController.php
  src/Form/ArticleSearchType.php
  templates/admin_section/index.html.twig
  templates/article/list.html.twig
  templates/home/_engagements.html.twig
Labels: Reviewed

#252 fix upload article
  src/Entity/Article.php
  src/Form/ArticleType.php
Labels: Reviewed

#254 padding outils
  templates/admin_tool/index.html.twig
Labels: Reviewed

#255 dev to master
  src/Entity/Article.php
  src/Form/ArticleType.php
  templates/admin_tool/index.html.twig
Labels: Reviewed

#256 Erreur flash edit outil fix
  src/Controller/AdminDocumentController.php
  src/Controller/AdminToolController.php
Labels: Reviewed

#258 dev to master
  .github/workflows/main.yml
  src/Controller/AdminDocumentController.php
  src/Controller/AdminToolController.php
Labels: Reviewed

#259 ajout et correction des messages flash
  src/Controller/AdminArticleController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminSectionController.php
  src/Controller/AdminTeamController.php
  src/Controller/AdminToolController.php
Labels: Reviewed

#260 dev to master
  src/Controller/AdminArticleController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminSectionController.php
  src/Controller/AdminTeamController.php
  src/Controller/AdminToolController.php
Labels: Reviewed

#262 changer le nom de la route dans le controller de la boite a outil
  src/Controller/AdminToolController.php
Labels: Reviewed

#261 Fix affichage section article OK
  assets/scss/home/article.scss
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#263 Delete tool document fix
  src/Entity/Document.php
Labels: Reviewed

#264 change assert article
  src/Entity/Article.php
Labels: Reviewed

#265 Responsive réparé
  templates/base.html.twig
Labels: Reviewed

#266 Dev to master
  assets/scss/home/article.scss
  src/Controller/AdminToolController.php
  src/Entity/Article.php
  src/Entity/Document.php
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/base.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#267 modif couleur suppression section
  src/Controller/AdminSectionController.php
Labels: Reviewed

#268 changes on admin article index
  assets/scss/admin/admin_article.scss
  templates/admin_article/index.html.twig
Labels: Reviewed

#281 fix BDD user access removed and template
  src/Controller/AdminUserController.php
  templates/admin_member/index.html.twig
Labels: Reviewed

#282 change browse button
  assets/scss/admin.scss
  assets/scss/app.scss
  templates/base.html.twig
Labels: Reviewed

#284 Fix nav logo
  assets/images/BOUSSOLE_BLANC.png
  assets/scss/_navbar_style.scss
  templates/_navbar.html.twig
Labels: Reviewed

#285 nouvelle charte déontologie
  assets/PDF/charte.pdf
  assets/PDF/plaquette.pdf
  templates/home/_engagements.html.twig
Labels: Reviewed

#286 Fix admin equipe responsive
  templates/admin_team/index.html.twig
Labels: Reviewed

#288 RGPD
  assets/scss/pages/register.scss
  src/Form/RegistrationFormType.php
  templates/security/register.html.twig
  templates/security/terms.html.twig
Labels: Reviewed

#287 bonnes offres
  templates/home/_deal.html.twig
Labels: Reviewed

#289 Fix section articles
  src/Entity/Article.php
  src/Entity/Section.php
  templates/admin_article/index.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#290 nouvelle plaquette synops
  assets/PDF/presentation.pdf
  assets/scss/home/adn.scss
  templates/home/_adn.html.twig
Labels: Reviewed

#291 "browse" changé pour "parcourir"
  templates/admin/index.html.twig
Labels: Reviewed

#308 actus ordered by date DESC
  src/Controller/AdminArticleController.php
Labels: Reviewed

#309 changes link
  templates/home/_adn.html.twig
  templates/home/_engagements.html.twig
Labels: Reviewed

#310 dev to master
  assets/PDF/charte.pdf
  assets/PDF/plaquette.pdf
  assets/PDF/presentation.pdf
  assets/images/BOUSSOLE_BLANC.png
  assets/scss/_navbar_style.scss
  assets/scss/admin.scss
  assets/scss/admin/admin_article.scss
  assets/scss/app.scss
  assets/scss/home/adn.scss
  assets/scss/pages/register.scss
  src/Controller/AdminArticleController.php
  src/Controller/AdminSectionController.php
  src/Controller/AdminUserController.php
  src/Entity/Article.php
  src/Entity/Section.php
  src/Form/RegistrationFormType.php
  templates/_navbar.html.twig
  templates/admin/index.html.twig
  templates/admin_article/index.html.twig
  templates/admin_member/index.html.twig
  templates/admin_team/index.html.twig
  templates/article/list.html.twig
  templates/article/show.html.twig
  templates/base.html.twig
  templates/home/_adn.html.twig
  templates/home/_article.html.twig
  templates/home/_deal.html.twig
  templates/home/_engagements.html.twig
  templates/security/register.html.twig
  templates/security/terms.html.twig
Labels: Reviewed

#311 fixtures removed access members
  src/DataFixtures/UserFixtures.php
  templates/admin_member/index.html.twig
Labels: Reviewed

#312 Fix section
  assets/scss/admin/admin_article.scss
  assets/scss/home/article.scss
  templates/admin_article/index.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#313 useless code
  templates/tool/index.html.twig
Labels: Reviewed

#314 Top sticky button reduced
  assets/scss/_arrow.scss
  templates/_backToTop.html.twig
Labels: Reviewed

#315 Fix tool access
  assets/scss/pages/tools.scss
  templates/tool/index.html.twig
Labels: Reviewed

#317 uniformisation des boutons côté visiteur/membre
  assets/scss/home/article.scss
  templates/article/list.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#318 Fix section articles
  templates/article/list.html.twig
  templates/home/_article.html.twig
Labels: Reviewed

#319 précision search label
  src/Form/ArticleSearchType.php
Labels: Reviewed

#320 Fix upload article
  src/Controller/AdminArticleController.php
  src/Entity/Article.php
Labels: Reviewed

#316 useless code
  templates/user/show.html.twig
Labels: Reviewed

#321 Reduction taille image Engagement
  assets/scss/home/engagements.scss
  templates/home/_engagements.html.twig
Labels: Reviewed

#322 Fix footer
  assets/scss/_footer.scss
  templates/home/_footer.html.twig
Labels: Reviewed

#324 fix upload partner
  src/Controller/AdminPartnerController.php
  src/Entity/Partner.php
Labels: Reviewed

#327 dev to master
  assets/scss/_arrow.scss
  assets/scss/_footer.scss
  assets/scss/admin/admin_article.scss
  assets/scss/home/article.scss
  assets/scss/home/engagements.scss
  assets/scss/pages/tools.scss
  src/Controller/AdminArticleController.php
  src/Controller/AdminPartnerController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Article.php
  src/Entity/Partner.php
  src/Form/ArticleSearchType.php
  templates/_backToTop.html.twig
  templates/admin_article/index.html.twig
  templates/admin_member/index.html.twig
  templates/article/list.html.twig
  templates/home/_article.html.twig
  templates/home/_engagements.html.twig
  templates/home/_footer.html.twig
  templates/tool/index.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#328 change upload team
  src/Controller/AdminTeamController.php
  src/Entity/Team.php
Labels: Reviewed

#330 fix carousel
  templates/home/_carousel.html.twig
Labels: Reviewed

#331 taille images engagements
  assets/scss/home/engagements.scss
Labels: Reviewed

#332 dev to master
  assets/scss/home/engagements.scss
  src/Controller/AdminTeamController.php
  src/Entity/Team.php
  templates/home/_carousel.html.twig
Labels: Reviewed

#333 Fix team, footer administrable
  src/Controller/HomeController.php
  src/DataFixtures/TeamFixtures.php
  src/Entity/Team.php
  templates/home/_footer.html.twig
  templates/home/_team.html.twig
Labels: Reviewed

#334 Fix upload tool
  src/Controller/AdminDocumentController.php
  src/Entity/Document.php
  src/Form/DocumentType.php
Labels: Reviewed
